### ISSUE TITLE
Request Reply

### ISSUE THREAD

**Issue by rameshglyton** [mateodelnorte/servicebus#106]
Does Service Bus support REQUEST REPLY kind of interaction between 2 microservices ?

**Comment by patrickleet** [comment]
You could probably use a promise. Initialize a `new Promise`, `send` a command, and `listen` for an event. When the event occurs, resolve the promise.

This approach would give you a unidirectional data flow and a similar request, reply style usage.

**Comment by mateodelnorte** [comment]
Yes. You can easily implement this yourself on top of servicebus as Patrick
is mentioning.

**Comment by campanagerald** [comment]
can you give an example?

**Comment by mateodelnorte** [comment]
process A on does a listen with a queueName of 'request'. process does a
listen with a queueName of 'response'. pretty much all you need, with sends
from each process.

**Comment by campanagerald** [comment]
can you give sample code?
