### ISSUE TITLE
heartbeat to reconnect to server on disconnect

### ISSUE THREAD

**Issue by mdsadiq** [mateodelnorte/servicebus#110]
i am using servicebus:2.0.10 in macOS Sierra
After servicebus has established connection and is subscribed to events, i restart the rabbitmq server.

servicebus does not detects and hence it stays disconnected

**Comment by mateodelnorte** [comment]
Once you've lost connection, the channel should throw an error. At this
point, you're better off throwing and restarting your process. You can read
more on crash oriented programming on both joyents website and the Nodejs
documentation.

You may be able to detect connection.close and recreate the connection, but
I wouldn't recommend it. From amqp's perspective, the channel is now closed.

**Comment by mdsadiq** [comment]
The channel is not throwing any error when connection is lost

**Comment by mdsadiq** [comment]
here is the test code with which i tried,
`const http = require('http')
const servicebusR = require('servicebus').bus
const config = require('./config/config')

http.createServer(app.callback()).listen(config.port + 1)
const rabbitmqurl = `amqp://${config.rabbitmq.username}:${config.rabbitmq.password}@${config.rabbitmq.host}?heartbeat=5`

const isRegistered = false
let busInstance = null

const servicebus = {
  register() {
    if (!isRegistered) {
      busInstance = servicebusR({ rabbitmqurl,
        exchangeName: config.rabbitmq.exchangeName,
        virtualHost: '/'
      })
    }
  },

  bus() {
    const localbus = servicebusR({ rabbitmqurl,
      exchangeName: config.rabbitmq.exchangeName,
      virtualHost: '/'
    })
    return localbus
  }
}

const ServiceBusHook = {
  init() {
    const servbus = servicebus.bus()
    servbus.subscribe(
      { queueName: config.queueName, routingKey: 'bygcrm.cb.payment' },
      { exchangeName: config.exchangeName },
      (msg, header) => {
        const routingKey = header.fields.routingKey.trim()
        console.log(`Received Event Routing Key ${routingKey}`)
        console.log(msg)
      }
		)
    process.on('close', (e) => {
      console.log('cleanup cleanupcleanup');
      console.log(e)
    });

    console.log(servbus)
  }
}

servicebus.register()
ServiceBusHook.init()
`

**Comment by mateodelnorte** [comment]
When I run your code, I get the following error. Including my slightly modified version of your code, just to remove reference to your other config file. 
```
RabbitMQBus {
  assertQueuesOnFirstSend: true,
  channels: [],
  correlator:
   Correlator {
     initialized: false,
     queues: {},
     filename: '/Users/mateodelnorte/development/servicebus/.queues',
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined },
  delayOnStartup: 10,
  formatter:
   { deserialize: [Function: deserialize],
     serialize: [Function: serialize] },
  initialized: false,
  log: { [Function: disabled] enabled: false, namespace: 'servicebus' },
  prefetch: undefined,
  pubsubqueues: {},
  queues: {},
  queuesFile: undefined,
  incomingMiddleware: [],
  outgoingMiddleware: [],
  domain: null,
  _events: { ready: [Function: bound subscribe] },
  _eventsCount: 1,
  _maxListeners: Infinity }
```
```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected close
    at succeed (/Users/mateodelnorte/development/servicebus/node_modules/amqplib/lib/connection.js:270:13)
    at onOpenOk (/Users/mateodelnorte/development/servicebus/node_modules/amqplib/lib/connection.js:252:5)
    at /Users/mateodelnorte/development/servicebus/node_modules/amqplib/lib/connection.js:165:32
    at /Users/mateodelnorte/development/servicebus/node_modules/amqplib/lib/connection.js:159:12
    at Socket.recv (/Users/mateodelnorte/development/servicebus/node_modules/amqplib/lib/connection.js:497:12)
    at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at emitReadable_ (_stream_readable.js:520:10)
    at emitReadable (_stream_readable.js:514:7)
    at addChunk (_stream_readable.js:280:7)
```
