### ISSUE TITLE
What is the difference between "listen" and "subscribe"?

### ISSUE THREAD

**Issue by ShaharyarAhmed** [mateodelnorte/servicebus#137]
What is the difference between `listen` and `subscribe`? Because under the hood both just `consume` the specified queue.

**Comment by remade** [comment]
`listen (queueName, options, callback)` consumes the queue `queueName` directly without using a routing key. You are sure there is a queue `queueName` and that queue has the messages you are interested in. However, `subscribe (queueName, options, callback)` uses the routingKey pattern to get matching messages and bind them to queue `queueName`. Send/Listen implements `direct` exchange and `Publish/Subscribe` `topic` exchange

The example below publishes the topic `info.one`
```
bus.publish("info.one", message, {
   // routingKey: "info.one", // Another way of setting topic
});
```
then asserts a queue `my_queue`, binds to all messages matching `info.*` routing key and consumes the queue
```
bus.subscribe('my_queue', {
    routingKey: "info.*"
}, function (message) {
    console.log(message)
})
```

**Comment by mateodelnorte** [comment]
Correct. The difference is the exchange type. As a result, send/listen will send to one queue or do round robin. Publish/subscribe will fan out/broadcast using topic routing. This is in the readme.
