### ISSUE TITLE
Multiple instances of a service subscribe to topic

### ISSUE THREAD

**Issue by kojuka** [mateodelnorte/servicebus#139]
@mateodelnorte awesome library.  Thanks for this.  Also thanks for your talk on youtube on CQRS.  If you haven't seen it, its the best most straight forward explanation on CQRS I've come across.  Here is the link: https://www.youtube.com/watch?v=4k7bLtqXb8c

I have a question:

Lets say I have the following setup:

**a1** and **a2** instances of account service 
**b1** instance of billing service
**u1** instance of user service

scenario:
**u1** publishes `user.created` event with payload

Here is what I want to happen but I can't figure out how to do it:

Either instance **a1** or **a2** to get the message and do work -- not both.
At the same time I also want instance **b1** to get the message and do work.

Any thoughts on how to accomplish this?  Thanks

**Comment by mateodelnorte** [comment]
Sounds like you want to `bus.publish('my.eventname', x, cb)` and have b1, a1, and a2 `bus.subscribe(` to it. You want a1 and a2 to round-robin distribute 50% load to each other, so you'll want them to share the same queue. You can do this by specifying queueName as well as routingKey on the subscribe: 
```
bus.subscribe({
  routingKey: 'my.eventname',
  queueName: 'a.my.eventname',
});
```

**Comment by mateodelnorte** [comment]
If you haven't found it before, check out https://github.com/mateodelnorte/servicebus-register-handlers. It makes configuring these types of handlers extremely easy, and is a bit of convention over configuration.

**Comment by kojuka** [comment]
Thats exactly what I needed.  Thank you!
