### ISSUE TITLE
Safe to .gitignore .queues on production

### ISSUE THREAD

**Issue by nicholaswmin** [mateodelnorte/servicebus#152]
Not sure what `.queues` file does. Is it safe to `.gitignore` it?

**Comment by mateodelnorte** [comment]
Yes. You want to .gitignore it.

The file is created to remember dynamically created subscription names in
the event you are not giving specific names to queues when subscribing.

If you don't provide a name for the queue, Rabbitmq will create a random
name for the queue. If your server crashes, it will come back up and be
given a new random queue, and messages in the old queue will just sit
there.

This file tells servicebus to map the event name in the subscriber to the
queue name received from RMQ so it doesn't ensure a new queue, but instead
subscribes to the original queue that already exists.
