### ISSUE TITLE
Is send/listen always 1:1?

### ISSUE THREAD

**Issue by nicholaswmin** [mateodelnorte/servicebus#155]
Hi again,

I've got a message I want to send from **server A** to **server B**.

Server B is running on multiple instances (think NodeJS cluster). 
I want **only 1 instance** of Server B to receive that event. 

If I understood correctly I need to use `send`/`listen` instead of `publish`/`subscribe`, is that correct?

**Comment by mateodelnorte** [comment]
Correct. Send/listen will use a single queue and listeners will get them an a round-robin fashion. This is good, for instance, for scaling horizontally. 

publish/subscsribe would cause all subscribers to get the message.
