### ISSUE TITLE
feature request: configure/get retry middleware's maxRetries

### ISSUE THREAD

**Issue by jrmurad** [mateodelnorte/servicebus#34]

**Comment by mateodelnorte** [comment]
This is configurable. Just pass { maxRetries: X } to the middleware constructor (in your bus.js file, for instance).

**Comment by mateodelnorte** [comment]
See the bottom of the retry.js file.

**Comment by jrmurad** [comment]
great, thanks! It would still be good to be able to get the value back (even the default). The use-case is for checking whether a particular event is the final retry. But I can compare against a self-configured setting for now.
