### ISSUE TITLE
correlationId not always available to llog

### ISSUE THREAD

**Issue by jrmurad** [mateodelnorte/servicebus#36]
Have to manually bind to process.domain.

**Comment by mateodelnorte** [comment]
If this is the case, it's simply because the current running context didn't have the process.correlationId set. This is not always obvious to spot, especially when using things like `async.queue`.

**Comment by mateodelnorte** [comment]
Unless you have an example, I'm tempted to close. Let me know if there's something I'm not thinking about.

**Comment by mateodelnorte** [comment]
Closing for now. Let's reopen if we see it again.
