### ISSUE TITLE
pub/sub doesnt work

### ISSUE THREAD

**Issue by schwrrring** [mateodelnorte/servicebus#49]
Dear Matt,

i am using servicebus pub-sub without success. 
publishing one event to two subscribers sends the event two the first, or to the second subscriber. Never to both subscribers.

I did quite a lot of research to handle the problem but cant find a solution. 
i use the pub - sub example from npm but with two subs -- it doesnt work.

**Comment by mateodelnorte** [comment]
Yep. That's a regression in the latest release. I'll fix it immediately and publish a new version. Thanks for spotting.

**Comment by mateodelnorte** [comment]
Are you running these from the same directory, perhaps? Can you cat the .queues files for each of the workers you're creating and paste them here?

sb creates a .queues file, in which dynamically created subscription names are stored. This allows your services to resubscribe to the same dynamically created queues when it restarts. If you're running them from the same directory, both of your apps will load their queues from the .queues file (starting from the 2nd time you run). You can either run them in different directories, provide a queuesFile path parameter, or provide a routingKey parameter on your subscriptions. The last option, there, will make the string you pass into subscribe be the name of the queue rabbit creates. 

In tracking this down, I did spot a bug - though I'm not sure if it's related to what you're seeing. I'll fix that and push shortly.

**Comment by mateodelnorte** [comment]
Just pushed servicebus@1.0.13 which fixed a related issue, but not what I think you're experiencing. 

I think, if you run your processes in different directories, you'll get what you're expecting. Go ahead and bump to 1.0.13 to get the other fixes.

**Comment by schwrrring** [comment]
Hey!
you fixed it :)
Great Job! 
The queue was empty, now there is something.
thank's alot!

**Comment by schwrrring** [comment]
May I ask you for one more favour? Could you explain me how to do the routingKey thing You wrote about?  "You can either run them in different directories, provide a queuesFile path parameter, or provide a routingKey parameter on your subscriptions."

I am very new to coding, and would be great, if you could help me a little.
best
malte

**Comment by mateodelnorte** [comment]
Just made another publish, to 1.0.14. This will actually help with what you're talking about in your last comment. 

Read up here for info on routingKeys and topic routing: https://www.rabbitmq.com/tutorials/tutorial-five-python.html

**Comment by schwrrring** [comment]
Hey!

thank's for the new publish and the link to the tutorial, which i start reading now. Thank's alot again for the great support! 

best 
malte

**Comment by mateodelnorte** [comment]
Sure thing. :D

If you want to help contribute, I'm super swamped with the system I'm currently building. If you want to help improve the readme, it would be an enormous help. 

You might even be able to create some slick documentation like http://expressjs.com/. It would be a huge help to the project, and in the process you'd end up knowing it inside and out. 

Up to you! Thanks for using it.

**Comment by schwrrring** [comment]
Hey Mat!
Sorry for the late response. 
I was very busy lately. It would be nice to be able to help but at the moment it will be hard to find free time. I will let u know, when that changes and be happy to help!

Best
Malte

**Comment by schwrrring** [comment]
Hey Mat,

I changed some things in my schedule and could start working on a tutorial/read me immediately.
I am at the moment doing an internship at a startup and could devote myself to the task completely for a while. Therefor it would be very helpful if we could talk via phone or skype (hamburgmalte). I am not yet a very skillful coder. That means I would ask you questions about things that I don't get from time to time. 
Would that be nevertheless interesting for you? 

I had the idea, that i write a tutorial similar and based on this one: https://www.rabbitmq.com/. Explaining how the tasks could be done with servicebus. 

Looking forward to hear from You and start working!
best
Malte

**Comment by mateodelnorte** [comment]
Hey Matte,

That sounds awesome. I'm pretty swamped at the moment, but we can definitely start off over IM. 

I like your idea on mimicking the rabbitmq tutorial. Do you have any ideas for how the overall site/page will look? Might be smart to base it on the design of another existing api that has a good look and feel. 

My email is mattwalters5 (_at_) gmail. Feel free to reach out. 

Thanks!

Matt

**Comment by mateodelnorte** [comment]
Fixed by #57
