### ISSUE TITLE
Unhandled rejection TypeError: next is not a function

### ISSUE THREAD

**Issue by armw4** [mateodelnorte/servicebus#65]
everything was working fine for us until the latest `1.0.21` patch was pushed. i believe this change in #64 is not quite backwards compatible and if desired, should result in a major release. can you advise?

**Comment by mateodelnorte** [comment]
Thanks for reporting @armw4. Can you paste your bus configuration here, including what middleware? 

Something like:

```
var config = require('cconfig')();
var servicebus = require('servicebus');
var retry = require('servicebus-retry');

var busUrl = var bus = servicebus.bus({
  prefetch: config.SERVICEBUS_PREFETCH,
  url: config.RABBITMQ_URL
});

bus.use(bus.messageDomain());
bus.use(bus.package());
bus.use(bus.correlate());
bus.use(bus.logger());
bus.use(retry({
  store: new retry.RedisStore({
    host: config.REDIS.HOST,
    port: config.REDIS.PORT
  })
}));

module.exports = bus;
```

**Comment by mateodelnorte** [comment]
My intention was to make the changes in #64 backward compatible by detecting whether incoming params matched the new signature, and adjusting where necessary, like: https://github.com/mateodelnorte/servicebus/pull/64/files#diff-88fd7a98e6a5a3b77dd077cbcc158c9eR52 However, if you have custom middleware, you might have to change the signature.

**Comment by armw4** [comment]
We do indeed have custom middleware. Shouldn't the major version have been bumped if it requires a signature change?

**Comment by armw4** [comment]
We downgraded to 1.0.18 so all is well on that front.

**Comment by armw4** [comment]
Or maybe you're not employing semver here?

**Comment by armw4** [comment]
we're using middleware of this flavor (presumably the older syntax)

```js
'use strict';

var _ = require('lodash');

function addMessageType (queueName, message, next) {
  var newMessage = _.assign(message, { type: queueName });

  next(null, queueName, newMessage);
}

module.exports = function () {
  return {
    handleOutgoing: addMessageType
  };
};
```

**Comment by mateodelnorte** [comment]
No, I'm employing semver. This should have been a major. Bumping minor was an oversight. 

I'll bump major and republish. I won't be able to unpublish 1.0.21 immediately, as we've got it deployed in production, but we plan to unpublish later this week once we do a hotfix for the bump.

**Comment by armw4** [comment]
@mateodelnorte ah great! thanks for this! we'll stick w/ `1.0.18` until we need to opt into new features.

**Comment by mateodelnorte** [comment]
Sweet. As for a little context, this was a fix that I've been pushing off for a while but adds a lot of capability. Previously, only incoming middleware had access to the options parameter - left over from the project's beginnings. This change finally brings outgoing middleware to parity with access to the options parameter. We use it to ensure we can set message properties like headers: 

```
Bus.send("my.event", { data: data }, {
  ack: true,
  correlationId: Bus.createCorrelationId(),
  headers: {
    audit: {
      action: 'my.action',
      index: { companyId: 'data.id' }
    }
  }
});
```
Which we use to programmatically publish audit messages when our message handlers complete, by using  https://github.com/mateodelnorte/servicebus-register-handlers 's onHandlerComplete option and https://github.com/electronifie/handle-audit.

**Comment by mateodelnorte** [comment]
Published to 2.0.0. Step one down.

**Comment by armw4** [comment]
Bet! I'd say it was definitely worth it. Glad to see ya'll are actively maintaining the project. Will you also be updating the `README` to illustrate what `v2.0.0` provides?

**Comment by armw4** [comment]
or a release/tag like https://github.com/mateodelnorte/servicebus/releases/tag/v2.0.0 would work. then you could edit the description and add details:

<img width="1193" alt="screen shot 2016-02-22 at 9 03 11 pm" src="https://cloud.githubusercontent.com/assets/246377/13242244/c9f52f94-d9a7-11e5-8d3e-901202780f3a.png">

**Comment by mateodelnorte** [comment]
I'll do my best to update the README this week as well. servicebus is very actively maintained. The current state of servicebus is in acting as the backbone of a new microservice framework we're developing. Everything is modular, replaceable, and follows simply but powerful patterns like https://github.com/mateodelnorte/servicebus-register-handlers. If you know anyone who'd like to help contribute to documentation, we'd be happy to have the help!

**Comment by armw4** [comment]
Solid! Thanks my man. I'll check out that service-register-handlers and will definitely elicit the bat signal re: docs if the opportunity presents itself.
