### ISSUE TITLE
Invalid example in readme

### ISSUE THREAD

**Issue by victor-homyakov** [mateodelnorte/servicebus#66]
Given example causes an error
```js
bus.listen('my.event', { ack: true }, function (event) {
  event.handle.acknowledge(); // acknowledge a message
  event.handle.ack(); // short hand is also available
  event.handle.reject(); // reject a message
});
```
because there is no `event.handle`

**Comment by mateodelnorte** [comment]
ack/reject requires the https://github.com/mateodelnorte/servicebus-retry middleware, which is mentioned in the note above the example. I'll make that more clear.
