### ISSUE TITLE
Example using `send` callback.

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/servicebus#73]
Hi Matt. Do you have any documentation on how to use the `RabbitMQBus.send` with the callback? Looking at the code, it seems coupled to the `confirmChannel` option and I'm not quite getting how that all works.

The use-case I'm looking at is a serial event chain where want to make sure that after processing one event, I've successfully sent it to the _next_ queue before ack-ing.

Thanks in advance.

**Comment by mateodelnorte** [comment]
Yup. The option is `enableConfirms`. Would be happy to have a README.md PR for it. 

Here's an example: 
```
var config     = require('cconfig')();
var servicebus = require('servicebus');

var bus = servicebus.bus({
  enableConfirms: true,
  prefetch: config.SERVICEBUS_PREFETCH,
  url: config.RABBITMQ_URL
});

module.exports = bus;
```

**Comment by mateodelnorte** [comment]
Note, `enableConfirms` enables the following functionality on RabbitMQ: https://www.rabbitmq.com/confirms.html. Without it, it's not possible to know when your message has been sent successfully.
