### ISSUE TITLE
TypeError: conn.createChannel is not a function

### ISSUE THREAD

**Issue by repkins** [mateodelnorte/servicebus#81]
Hello!

I encountered a weird issue regarding while testing connections to RabbitMQ. For example when I trying to connect stopped instrance of RabbitMQ service, I expecting to catched `ECONNREFUSED`, emited with on 'error' event. That's ok, but there for some reason it also throws unhandled exception `TypeError: conn.createChannel is not a function`, crashing application. I've made research for that problem and I've discovered that error comes from ".done" handler on making connection through amqplib module. That handler called  with passed **undefined** `conn` argument, which should not meant to be executed at all, if it is rejected;

I know how to fix, based of my deeper research, including amqplib module and its depedency module `when` so im ready to make pull request. Because for me its needed to get fixed ASAP.

**Comment by mateodelnorte** [comment]
Please do. PR's with tests are very welcome. :)

**Comment by mateodelnorte** [comment]
Fixed by #82
