### ISSUE TITLE
Pub/Sub acts like Round Robin

### ISSUE THREAD

**Issue by mbonig** [mateodelnorte/servicebus#84]
I've tried setting up a pub/sub setup with retry and what I'm seeing is that when a message is published to the bus, only one of my subscribers will get the message. On a second publish, the second subscriber gets the message and the first does not. A third message and now the first subscriber gets the message and the second doesn't. This continues indefinitely.

Here is my relative code:

```
 bus.subscribe(listener.event, (data, event) => {
            console.log(`subscriber is calling listener`);
            listener.handler(data, event)
                .then(() => {
                    //console.log('acking message after ');
                    console.log('!NOT! acking message after ');
                    //data.handle.ack();

                })
                .catch(err => {
                    data.handle.reject(err);
                });
        });
```

where my first subscriber/listener looks like this:

```
const Q = require('q');

module.exports = function () {
    const listener = this;

    listener.event = 'order.created';
    listener.handler = function (order, message) {
        console.log('Got an order! outputting purely as test:');
        console.log(order);
        return Q.promise((res,rej)=>{
            res();
        });
    };
    return listener;

};
```

my second one looks similar.

and my bus is called as a factory:

```
'use strict';

module.exports = function (options) {

    const bus = require('servicebus').bus(options || {});
    const retry = require('servicebus-retry');
    const config = require(require('path').resolve('./config/config'));

    bus.use(retry({
        store: new retry.RedisStore({host: config.redis.host, port: config.redis.port})
    }));

    console.log('initializing bus');


    return bus;
};
```

Using the pub/sub I was specifically looking for a durable (non-auto-delete queues, so use ack:true, just not here as debuggging) way of fanning out messages. I believe the docs suggest both my listeners should get each a message for 'order.created'.

Have I setup something wrong?

**Comment by mateodelnorte** [comment]
Are you sure you're using bus.publish() to send your messages and not bus.send()?

**Comment by mateodelnorte** [comment]
Also, it looks like you're recreating a lot of code found in https://github.com/mateodelnorte/servicebus-register-handlers. Might consider using it to add some structure to your projects.

**Comment by mbonig** [comment]
I am using .publish().

I'll double check and see if I can use that other projects and let you know. 

Thanks!

**Comment by mateodelnorte** [comment]
My bet is you initially created the queue you're currently publishing to
with `listen`, and since it's `ack:true` it's still performing as it should
and round robin-ing.

You can check your management portal to be sure and either delete the queue
or restart your broker to fix.

**Comment by mbonig** [comment]
I did once create the queue with ack:true, but if that queue is still around when go back, I get a stopping error that the queue isn't setup right. I've deleted the queue. Trying that other project now...

**Comment by mbonig** [comment]
Ok, so tried that registration helper:

```
 registerHandlers({
        bus: bus,
        handleError: function handleError (msg, err) {
            log.error('error handling %s: %s. rejecting message w/ cid %s and correlationId %s.', msg.type, err, msg.cid, this.correlationId);
            log.error(err);
            msg.handle.reject(function () {
                throw err;
            });
        },
        onHandlerCompleted: function(){console.log('finished handling')}, // publish auditing message after handler completed
        path: path.resolve('./services/subscribers/listeners'),   // load all handlers defined in the provided directory
        queuePrefix: '' // prepend all subscribe queue names with provided string
    });
```

where the two listeners I have are:

```

module.exports = {
    ack: true,
    queueName: 'order.created.test',
    routingKey: 'order.created',
    subscribe: function (order, next) {
        console.log('Got an order! outputting purely as test:');
        console.log(order);
        next();

    }
};
```

```
console.log('creating update portfolio listener');
module.exports = {
    ack: true,
    queueName: 'order.created.portfolio',
    routingKey: 'order.created',
    subscriber: function (order, next) {
        console.log(`handling the update of the portfolio (add or remove products) for order ${order._id}`);
      //removed for brevity
    }
};
```

I can see the order.created.test queue exist in rabbitmq, but I don't see the order.created.portfolio. Am I misusing the routingKey?

**Comment by mateodelnorte** [comment]
Your second handler says `subscriber` instead of `subscribe`. 😉

**Comment by mbonig** [comment]
And this is the ONE time I wish I was using Typescript.

Thanks. Made that change and it's all working as expected. Thanks!

BTW, do you recommend that each subscriber sets it's own unique queue name?

**Comment by mateodelnorte** [comment]
It depends, usually on concurrency and ordering. If you have events by
different names that must remain ordered, they must share a queue. That
will end up helping determine your message names.

**Comment by mateodelnorte** [comment]
By the way, was perusing through issues and it occurred to me - the behavior you were seeing was likely caused by having two bare subscribes in the same process. Doing so caused servicebus to 1st subscribe and record the queuename used in the local .queues file. Moments later, the 2nd subscribe ended up using the same mapped queue name, instead of a 2nd newly created queue. 

Using servicebus-register-handlers helped you get around the issue because it only binds one consumer for the routing key. It's smart enough to take that one message and run it through a pipeline of handlers. It's one of the reasons I created s-r-h.

**Comment by mbonig** [comment]
Makes sense. I figured there was something in my setup that was throwing it off...
