### ISSUE TITLE
Allow to read existing queues.

### ISSUE THREAD

**Issue by aangelidis** [mateodelnorte/servicebus#92]
Unless I missed something, the queues are completely managed by servicebus.

bus.subscribe('foo.bar', options, (msg) => {
});

This will create a queue as foo.bar.8aadae7d-bd7e-4dc7-ba85-f57a102b06fe.

Is it possible to tell it to use an existing queue?

For instance we want to pre create the queue let it fill up and when the application finished loading it then starts to read the queue.

**Comment by mateodelnorte** [comment]
bus.subscribe({ routingKey: 'foo.bar', queueName: `${process.env.
SERVICE_NAME_OR_SOMETHING_LIKE_IT}-foo.bar` }, options, (msg) => {
});

If you use servicebus-register-handlers, there is a queuePrefix property to
do the same thing globally on all subscribes.

**Comment by aangelidis** [comment]
Ok cool.

bus.subscribe({ routingKey: 'foo.*', queueName: 'foo.bar.baz', ack: true, queueOptions: {autoDelete: false }}, (msg) => {
});

Though it doesn't seem to allow to mark the queue as autoDelete: false

**Comment by aangelidis** [comment]
Never mind it would be pre-created lol!

**Comment by aangelidis** [comment]
But yeah it works thanks.
