### ISSUE TITLE
Publish/subscribe with many subscribers fails?

### ISSUE THREAD

**Issue by gfot** [mateodelnorte/servicebus#99]
From documentation I understood that if we have a publish/subscribe bus, then for one/same event published _all_ subscribers should receive it. If that's hold true, then the simple example presented in publish/subscribe section does not work properly.

**Comment by mateodelnorte** [comment]
You're probably running all the subscribers in the same directory, causing
them to all use the same .queues file, causing them to all use the same
named queue... which will then cause then to round robin.

Run them in different directorios, specify a different .queues file name
for each process, or specify a different queue name for each process'
subscribe.

**Comment by gfot** [comment]
Thanks for clarifying this. Indeed I executed all subscribers from the same directory.
